const GUN_CRATES_DATA = [

  ...GUN_CRATE_AK_47,
  ...GUN_CRATE_UZI,
  ...GUN_CRATE_RPG_7,
  ...GUN_CRATE_UMP_45,
  ...GUN_CRATE_AWM,
  ...GUN_CRATE_GLOCK_18C,
  ...GUN_CRATE_M4A1,
  ...GUN_CRATE_AUG_A1,
  ...GUN_CRATE_BENELLI_M1014,

];