const MISSIONS_DATA = [
  // Game Missions
  ...MISSIONS_GAME_BANK_HEIST,
  ...MISSIONS_GAME_GET_ROLLING,

  // Bert Missions
  ...MISSIONS_BERT_COMMUNITY_OUTREACH,
  ...MISSIONS_BERT_STOLEN_GOODS,
  ...MISSIONS_BERT_SERVICE_FEE,
  ...MISSIONS_BERT_COUNTER_INTEL,

  // Erik Missions
  ...MISSIONS_ERIK_ARTISAN,

  // Dan Missions
  ...MISSIONS_DAN_FORBIDDEN_MEAT,

  // Sir B Missions
  ...MISSIONS_SIR_B_CONTRABAND,
  ...MISSIONS_SIR_B_CRIME_SQUAD,
  ...MISSIONS_SIR_B_DATA_DISK,
  ...MISSIONS_SIR_B_FENCE,
  ...MISSIONS_SIR_B_FRONT_TOWARD_ENEMY,
  ...MISSIONS_SIR_B_FUEL_DEPOT,
  ...MISSIONS_SIR_B_GEM_COLLECTOR,
  ...MISSIONS_SIR_B_GOING_LOUD,
  ...MISSIONS_SIR_B_HIDDEN_CARGO,
  ...MISSIONS_SIR_B_INCRIMINATING_DATA,
  ...MISSIONS_SIR_B_LIGHTS_OUT,
  ...MISSIONS_SIR_B_LOCKPICKER,
  ...MISSIONS_SIR_B_MOST_WANTED,
  ...MISSIONS_SIR_B_NIGHTSTALKER,
  ...MISSIONS_SIR_B_OASIS_ELEVEN,
  ...MISSIONS_SIR_B_PAYDAY,
  ...MISSIONS_SIR_B_PHANTOM,
  ...MISSIONS_SIR_B_RING_COLLECTOR,
  ...MISSIONS_SIR_B_SMUGGLER,
  ...MISSIONS_SIR_B_STEALTH_PILOT,
  ...MISSIONS_SIR_B_SYNDICATE_DOGS,
  ...MISSIONS_SIR_B_SUBMARINER,
  ...MISSIONS_SIR_B_TELLER,
  ...MISSIONS_SIR_B_THE_DEPOSIT,
  ...MISSIONS_SIR_B_THE_ESTATE,
  ...MISSIONS_SIR_B_THE_FILES,
  ...MISSIONS_SIR_B_THE_HEAVIEST_BAG,
  ...MISSIONS_SIR_B_TIMEPIECE,
  ...MISSIONS_SIR_B_UPGRADE,
  ...MISSIONS_SIR_B_WARGAMES,
  ...MISSIONS_SIR_B_WEAPONS_CACHE,

  // Easter Missions
  ...MISSIONS_EASTER_THE_EGG_HUNT,
  ...MISSIONS_EASTER_SYNDICEGG,

  // Christmas Missions
  ...MISSIONS_CHRISTMAS_SANTAS_HELPER,
  ...MISSIONS_CHRISTMAS_TOY_DRIVE,
  ...MISSIONS_CHRISTMAS_JINGLE_BALLS,
];
