const VALUABLES_DATA = [
  ...VALUABLES_GEMS,
  ...VALUABLES_JEWELRY,
  ...VALUABLES_ELECTRONICS,
  ...VALUABLES_TECH,
  ...VALUABLES_SHOES,
  ...VALUABLES_MISCELLANEOUS,
  ...VALUABLES_MISSION_ITEMS,
  ...VALUABLES_EASTER,
];

const EASTER_VALUABLES_DATA = [
  ...VALUABLES_EASTER,
];

const CHRISTMAS_VALUABLES_DATA = [
  ...VALUABLES_CHRISTMAS,
];

const FOURTH_OF_JULY_VALUABLES_DATA = [
  ...VALUABLES_4TH_OF_JULY,
];
