const VEHICLES_DATA = [

  // Ground Vehicles
  ...VEHICLE_CRUISER,
  ...VEHICLE_NOMAD,
  ...VEHICLE_RANGER,
  ...VEHICLE_CONTENDER,
  ...VEHICLE_BEAM,
  ...VEHICLE_CROWLINE,
  ...VEHICLE_STALLION_450,
  ...VEHICLE_G_CRUISER,
  ...VEHICLE_GEMSTONE,
  ...VEHICLE_VANGUARD,
  ...VEHICLE_ZORO,
  ...VEHICLE_PULSE_477,
  ...VEHICLE_RAZOR,
  ...VEHICLE_ZORVELLO,
  ...VEHICLE_SPECTRE,
  ...VEHICLE_BLADE,
  ...VEHICLE_ROKU,
  ...VEHICLE_HORIZON,
  ...VEHICLE_TEMPORO,
  ...VEHICLE_PULSE_477_RS,
  ...VEHICLE_EMPYREAN,
  ...VEHICLE_FALCON_GT,
  ...VEHICLE_RIVAL,
  ...VEHICLE_MOCHI,

  // Flying Vehicles
  ...VEHICLE_MINI_BIRD,
  ...VEHICLE_SCOUT,
  ...VEHICLE_PANTHER,

];